### PR TITLE
show diacritics in email subject

### PR DESCRIPTION
**Pull request by Quentinchampenois**
**Describe the bug**
When an event is sent by email, if the resource title has diacritics, then characters are escaped. 

**To Reproduce**
1. Log in as user
2. Enable `email_on_notification` option in "My account" section
3. Go to a Process
4. Create a new proposal with diacritics in title, "It's a new proposal" for example
5. With an other account creates a comment on the newly created proposal
6. Check letter_opener
4. See email subject as "It&#39;s a new proposal"

**Expected behavior**

In the "step to reproduce" context, I would like to have in email subject "It's a new proposal" rather than "It&# 39 ;s a new proposal".

**Screenshots**
Screenshot 2021-04-12 at 15 42 36

### CODE REVIEW

**Comment by paulinebessoles** [comment]
Tested and approved by product! Thanks @Quentinchampenois 

I also wondered if this could be link to the following problem: 
When the proposal body contains a # (hashtag), it's rendered in the mail body like this: `gid://development-app/Decidim::Hashtag/1/proposal`

Capture d’écran 2021-04-12 à 16 29 13
Capture d’écran 2021-04-12 à 16 29 07

If this can be fixed in the same PR, that's cool, otherwise we'll wait next sprint

**Comment by Quentinchampenois** [comment]
> I also wondered if this could be link to the following problem:
> When the proposal body contains a # (hashtag), it's rendered in the mail body like this: `gid://development-app/Decidim::Hashtag/1/proposal`

> If this can be fixed in the same PR, that's cool, otherwise we'll wait next sprint

Okay, I check if I can fix it here

**Review by paulinebessoles — APPROVED** [review]

**Comment by Quentinchampenois** [comment]
> > If this can be fixed in the same PR, that's cool, otherwise we'll wait next sprint
> 
> Okay, I check if I can fix it here

I will investigate this point on Decidim `develop` branch

**Review by armandfardeau — CHANGES_REQUESTED** [review]
Hi @Quentinchampenois Is it possible to have a test with this?

**Comment by Quentinchampenois** [comment]
Draft for now because I have to add tests in project

**Pull request closed without merging**
